### ISSUE TITLE
please support non 6 strings

### ISSUE THREAD

**Issue by sugizo** [0xfe/vextab#114]
nice to have non 6 strings tablature e.g. 4 - 12 strings
because out there have bass tablature too
thx
perhaps in **src/artist.coffee**
strings: 6 // should be variable that passing by an argument

**Comment by 0xfe** [comment]
You can add `strings=4` to `tabstave` for bass (or any other number between 4 and 8).

E.g., `tabstave notation=true key=A time=4/4 strings=4`

**Comment by nlahmi** [comment]
This is only partially fixed, as tab notation (even with 4 strings) seems to use guitar octaves so.. you either have to write `fret/string` and only render the tab view or write using `note/octave` and only render sheet music - it's not synchronized!

**Comment by KevinGage** [comment]
> This is only partially fixed, as tab notation (even with 4 strings) seems to use guitar octaves so.. you either have to write `fret/string` and only render the tab view or write using `note/octave` and only render sheet music - it's not synchronized!

Yes please.  I just discovered this plugin and would love to use it for bass guitar notation and tab.  But when I do something like this

```vextab
tabstave notation=true tablature=true clef=bass strings=4
notes :16 5-5-5-5/4 ## 5-5-5-5/4 #7#
```

I get this where the octave is way off.
![image](https://github.com/0xfe/vextab/assets/10852792/bd9a89e0-99fb-426d-8cf8-8695d77261cb)
