### ISSUE TITLE
my.vexflow.com is down

### ISSUE THREAD

**Issue by jlmagee** [0xfe/vextab#115]
I cannot connect to it with either http or https.  Based on the vextab readme, there is some reference information there.

**Comment by jzohrab** [comment]
Confirmed still down Apr 14 2021.  The readme has these broken links:

* http://my.vexflow.com/
* "take a look at the list of features" = http://my.vexflow.com/articles/53?source=enabled

**Comment by 0xfe** [comment]
Thanks. I'm not operating it anymore :-) I'll remove the references.
