### ISSUE TITLE
Notation and tab not aligned

### ISSUE THREAD

**Issue by infojunkie** [0xfe/vextab#117]
When I write
```
tabstave notation=true key=E time=4/4

notes :8 (14/1.11/3) $B7$ (16/1.13/3) (12/1.9/3) :q (9/1.6/3) $F♯m7$ :8 (11/1.8/3) :q (7/1.0/2) $B7$ |
notes :8 (2/1.4/4)   $B7$ (4/1.1/3)   (0/1.2/4)  :q (2/2.4/5) $F♯m7$ :8 (4/2.1/4)  :q (0/2.2/5) $B7$ |
notes :8 (4/4.2/6)   $B7$ (6/4.4/6)   (2/4.0/6)  :q 4/5 $F♯m7$ :8 1/4 0/4 $B7$ 4/5 |
notes :w 2/5 $B7$ |
```
I get this:

![attached screenshot](https://user-images.githubusercontent.com/92977/106098187-7a483400-60ed-11eb-8707-dae56f32d602.png)

Am I doing something wrong? Using `3.0.6`

**Comment by louisantoinem** [comment]
The broken alignment is due to the final "|" sign. 
Remove this final "|" or apply the following fix: https://github.com/0xfe/vextab/issues/99#issuecomment-362538056

**Comment by infojunkie** [comment]
That worked, thanks! Closing this as duplicate of #99
