### ISSUE TITLE
Compiled library is very big

### ISSUE THREAD

**Issue by ericman314** [0xfe/vextab#73]
This is an impressive library!

I'm making a mobile flashcard app for some orchestra students, and I found your library was a perfect fit for what I need. However, the compiled library is 1.4 MB, which is pretty big for a mobile app.

Is there any way to select only the features I need to reduce the size of the library? For example, all I need to render is the staff, clef, key signature, and a single note.

Thanks!

**Comment by 0xfe** [comment]
No way to select features right now (but you can mess with the build scripts to take out stuff that you're not using.)

Alternatively, minifying and gzipping the library could significantly drop the total size (by ~90%), and you can use http transfer encoding: gzip to serve it.
